Сделал SSR
yandex-praktikum/client-server-template-with-vite pull request #31
Opened 2023-06-02 08:57 UTC by zorox112

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-02 08:58 UTC, zorox112 commented on Dockerfile.server
> +COPY --from=builder /app/packages/server/dist/ /app/server
Делаем одинаковый уровень вложенности у серверного приложения в проде (с докером и без докера)

2023-06-02 09:01 UTC, zorox112 commented on packages/server/index.ts
> +  const pathToClient = path.join(__dirname, '../client')
dev режим в любом случае будет ходить в папку client. А делать зависимость client -> shared -> server такое себе, хочется, чтобы в shared не мог попадать код какого модуля до билда, должны быть разрешены только импорты из shared

2023-06-02 09:03 UTC, zorox112 commented on packages/server/index.ts
> +async function startServer() {
Оборачиваем из-за наличия async функций у сборщика

2023-06-05 06:22 UTC, khitrind requested changes

2023-06-05 06:22 UTC, khitrind commented on packages/client/src/App.tsx
> +const users = ['Коля', 'Петя', 'Степа', 'Лиза']
Мы не хотим это прокинуть из сервера?

2023-06-05 06:22 UTC, khitrind commented on packages/client/src/main.tsx
> +  document.getElementById('root') as HTMLElement,
Тут бы я через проверку делал, что элемент есть

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +    if (isDev()) {
Почему два ифа с isDev?

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +    if (isDev()) {
Я бы просто вынес логику в дые функции, которые возвращают render

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +        await vite!.ssrLoadModule(
зачем тут `!`?

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +  createClientAndConnect()
Вот это точно должно быть тут?

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +  const pathToClient = path.join(__dirname, '../client')
Это я бы тоже вынес за пределы старта сервера. Просто наверх модуля, что бы тут была только логика

2023-06-05 06:22 UTC, khitrind commented on packages/server/index.ts
> +    const appHtml = await render()
Всю try{}catch везде пропустили

2023-06-06 14:26 UTC, zorox112-practicum commented on packages/client/src/App.tsx
> +const users = ['Коля', 'Петя', 'Степа', 'Лиза']
Пока что нет, так как у них будет отдельный урок по тому, как работать со стором, хочется сразу там перенести это на сервер, а потом положить в стор

2024-09-22 11:20 UTC, closed without merging